### ISSUE TITLE
A couple of ejector issues

### ISSUE THREAD

**Issue by Botspot** [raspberrypi-ui/lxplug-ejecter#2]
See: https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=277006
If I understood the code better I'd fix it myself.

**Comment by spl237** [comment]
The behaviour is fundamentally limited by the information available from the GIO Volume Monitor. In spite of rewriting it several times, this is the best I have been able to achieve in terms of reliability and accurate reporting. Unless you can actually submit PRs which show demonstrable improvements, I won't be making any changes.
